/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#007751",
        "on-surface": "#151c27",
        "inverse-primary": "#aac7ff",
        "secondary-fixed": "#7df5f5",
        "surface-dim": "#d3daea",
        "surface-container-highest": "#dce2f3",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "surface": "#f9f9ff",
        "primary-fixed": "#d7e3ff",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#dfe8ff",
        "inverse-surface": "#2a313d",
        "on-secondary-fixed-variant": "#004f4f",
        "surface-container": "#e7eefe",
        "secondary": "#006a6a",
        "outline-variant": "#c1c6d5",
        "on-surface-variant": "#414753",
        "primary-container": "#0066cc",
        "surface-container-low": "#f0f3ff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#00458e",
        "tertiary": "#005c3e",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9ff",
        "outline": "#727784",
        "on-secondary-container": "#006e6e",
        "on-secondary-fixed": "#002020",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#83ffc6",
        "background": "#f9f9ff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-container-high": "#e2e8f8",
        "inverse-on-surface": "#ebf1ff",
        "secondary-fixed-dim": "#5dd9d8",
        "on-primary-fixed": "#001b3e",
        "primary-fixed-dim": "#aac7ff",
        "primary": "#004e9f",
        "secondary-container": "#7af2f2",
        "on-tertiary-fixed-variant": "#005236",
        "on-background": "#151c27",
        "tertiary-fixed": "#6ffbbe",
        "surface-variant": "#dce2f3",
        "surface-tint": "#005cba"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "margin-desktop": "32px",
        "gutter": "24px",
        "stack-lg": "24px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "tabular-nums": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "tabular-nums": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
